### PR TITLE
Exercise gh-actions to identify any gaps in functionality

### PR DESCRIPTION
**Pull request by phpisciuneri**

### CODE REVIEW

**Comment by phpisciuneri** [comment]
It seems that the action was triggered and completed successfully: https://github.com/target/data-validator/runs/138915693

But the status was never reported.

**Comment by phpisciuneri** [comment]
@dougb we appear to be running into this problem:

> GitHub Actions and forked repositories are currently in a weird state. I expect this to improve quickly, but right now when a pull request is opened from a fork to the upstream, there are a few oddities. The first is that it will only trigger the pull_request event - that makes sense because the associated push isn’t happening on the upstream repo. However, this leads to the actual issues: the tests are run against the master branch, and the status isn’t reflected back to the pull request.

https://jasonet.co/posts/use-github-actions-for-ci/#running-ci-on-pull-requests-from-forks

This is exactly what I am seeing.  All [actions](https://github.com/target/data-validator/actions) appear to be on the master branch, and the status isn't getting reported back.

**Comment by phpisciuneri** [comment]
After some more reading, it seems that this is the intended behavior:

- https://github.community/t5/GitHub-API-Development-and/Run-a-GitHub-action-on-pull-request-for-PR-opened-from-a-forked/td-p/15426 
- https://developer.github.com/actions/managing-workflows/workflow-configuration-options/#pull-request-events-for-forked-repositories

> If you intend to use the pull_request event to trigger CI tests, it's recommended to listen to the push event.

**Comment by colindean** [comment]
This is outdated now.

**Pull request closed without merging**
