### PR TITLE
extend JsonUtils for doubles

### LINKED ISSUE #53: SQL variable substitution fails when result is a double
Observed, for example, when combined with `ColumnSumCheck`.  See example config below:

```yaml
---
numKeyCols: 2
numErrorsToReport: 1
detailedErrors: true

vars:
  - name: MAX_AGE
    sql: SELECT CAST(MAX(age) AS DOUBLE) FROM census_income.adult

outputs:
  - filename: report.json
    append: false

email:
  smtpHost: smtp.example.com
  subject: Data Validation Summary
  from: data-validator-no-reply@example.com
  to:
    - person1@example.com

tables:
  - db: census_income
    table: adult
    checks:
      - type: columnSumCheck
        column: age
        minValue: $MAX_AGE
        inclusive: true
```

yields:

```
...
...
21/01/14 09:12:01 ERROR JsonUtils$: Unimplemented dataType 'double' in column: CAST(max(age) AS DOUBLE) Please report this as a bug.
21/01/14 09:12:01 INFO ValidatorConfig: substituteVariables()
21/01/14 09:12:02 INFO Substitutable$class: Substituting Json minValue Json: "$MAX_AGE" with `null`
...
...
21/01/14 09:12:02 ERROR ColumnSumCheck$$anonfun$configCheck$1: 'minValue' defined but type is not a Number, is: Null
21/01/14 09:12:02 ERROR ValidatorTable$$anonfun$1: ConfigCheck failed for HiveTable:`census_income.adult`
...
...
```

### PR DESCRIPTION
**Pull request by phpisciuneri**

### CODE REVIEW

**Comment by phpisciuneri** [comment]
@colindean @c-horn @samratmitra-0812 Can we expedite review here if possible?  It is a small change and currently a blocker for a user.

**Comment by samratmitra-0812** [comment]
@phpisciuneri If I understand correctly, this is to support the use case where a sql used for variable substitution returns a double. Is that correct?

**Comment by samratmitra-0812** [comment]
@phpisciuneri My bad. I see that you have already linked the PR to the issue.

**Review by samratmitra-0812 — APPROVED** [review]
LGTM

**Review by colindean — APPROVED** [review]

**Pull request merged**
