### PR TITLE
add a convention for loading yaml config files from the classpath

### PR DESCRIPTION
**Pull request by c-horn**
Instead of explicitly including the config file with `spark-submit` like:
```bash
spark-submit --file config_file.yaml data-validator.jar --config config_file.yaml
```

If the yaml file is already on Spark's driver classpath (for instance in a jar compiled from a `resources/` directory included in a package added with `--packages` or `--jars`), you can reference it:
```bash
  --config classpath:/config_file.yaml
```

### CODE REVIEW

**Comment by c-horn** [comment]
@dougb ^

**Comment by dougb** [comment]
I asked @c-horn to make one more change [here](/target/data-validator/blob/master/src/main/scala/com/target/data_validator/Main.scala#L138)  to add some text  about the classpath config feature.

**Comment by colindean** [comment]
I don't have merge perms on this repo (yet). Can you add me or merge it, @dougb or @phpisciuneri?

**Comment by phpisciuneri** [comment]
@colindean we were trying to get the CI sorted out.  Sorry for the delay.

@dougb @c-horn merging branch master into this PR didn't seem to trigger any action.  The status check is still waiting for `compile data-validator` action.  I am just going to merge.  We can sort this out with a fresh PR.

**Pull request merged**
